### ISSUE TITLE
About the two trainable conv layers.

### ISSUE THREAD

**Issue by Colezwhy** [wysoczanska/clip_dinoiser#3]
Hi, Thank you for your wonderful works! Which is very inspiring to me.
And I wonder whether replace the two conv layers with more sophisticated modules or layers can bring more benefit or not.
Because the conv layer is just way too simple.

**Comment by osimeoni** [comment]
Dear @Colezwhy, 

Thanks for the question and the interest in the work. 
During this work we aimed for the lightest modules possible, hence the usage of simple conv3x3 and conv1x1. 

In order to learn DINO correlations (conv3x3), we did play with slightly bigger models but without obvious gain. With this conv layer, we aim at producing intermediate features which _correlations_ are alike those of DINO, we actually do not use the features themselves, which might explain why bigger layers did not obviously help. It was however important to use a conv3x3 rather than a conv1x1 in order to have more local context.  

Regarding the foreground segmentation, FOUND layer is also a conv1x1 applied onto DINO. We were happily surprised that such a simple transformation applied to CLIP features would allow us to produce an objectness map (showing that CLIP already contains good quality localization properties) and we did not play further. 

Bigger models might indeed benefit, but maybe alongside slightly different objectives. Let us know if you play with them !

**Comment by Colezwhy** [comment]
> Dear @Colezwhy,
> 
> Thanks for the question and the interest in the work. During this work we aimed for the lightest modules possible, hence the usage of simple conv3x3 and conv1x1.
> 
> In order to learn DINO correlations (conv3x3), we did play with slightly bigger models but without obvious gain. With this conv layer, we aim at producing intermediate features which _correlations_ are alike those of DINO, we actually do not use the features themselves, which might explain why bigger layers did not obviously help. It was however important to use a conv3x3 rather than a conv1x1 in order to have more local context.
> 
> Regarding the foreground segmentation, FOUND layer is also a conv1x1 applied onto DINO. We were happily surprised that such a simple transformation applied to CLIP features would allow us to produce an objectness map (showing that CLIP already contains good quality localization properties) and we did not play further.
> 
> Bigger models might indeed benefit, but maybe alongside slightly different objectives. Let us know if you play with them !

Thank U very much! I will close this.
